server:
  port: 80

spring:
  #  messages:
  #    encoding: UTF-8
  #    basename: messages,error

  datasource:
    url: jdbc:h2:tcp://localhost/~/blog_search
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true